[package]
name = "binpatcher"
version = "0.1.1"
authors = ["Vasyl Zhushma <vazhushma@gmail.com>"]
edition = "2021"

[dependencies]
winapi = { version =  "*", features = ["winnt"] }

[[example]]
name = "dylib"
path = "examples/dylib/lib.rs"
crate-type = ["cdylib"]
